[workspace]
members = ["dirigent_desktop", "dirigent_launcher", "dirigent_server"]
default-members = ["dirigent_desktop"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"

[patch.crates-io]
# Includes the unreleased fix for Rust's `pub_use_of_private_extern_crate` warning.
proc-macro-error2 = { git = "https://github.com/fgardt/proc-macro-error-2", rev = "53ff94b61c678593158db1a3d50269c6f0de0db7" }
